CXX = gcc
CFLAGS = -I ../utils
OUTFILE = -o $@.out
INFILE = $@.c
UTILS = ../utils
STDPATTERN = $(CXX) $(CFLAGS) $(OUTFILE) $(INFILE)

02-01:
	$(STDPATTERN) $(UTILS)/BitVector.c $(UTILS)/LinkedList.c
02-02:
	$(STDPATTERN) $(UTILS)/LinkedList.c
02-03:
	$(STDPATTERN) $(UTILS)/LinkedList.c
02-04:
	$(STDPATTERN) $(UTILS)/LinkedList.c
02-05:
	$(STDPATTERN) $(UTILS)/LinkedList.c
clean:
	rm *.out
