test:
	gcc -I utils tests/BitVectorTest.c utils/*.c -o tests/BitVectorTest.out &&\
	gcc -I utils tests/LinkedListTest.c utils/*.c -o tests/LinkedListTest.out &&\
	gcc -I utils tests/StackTest.c utils/*.c -o tests/StackTest.out &&\
	gcc -I utils tests/LinkedListGenericTest.c utils/*.c -o tests/LinkedListGenericTest.out &&\
	gcc -I utils tests/QueueTest.c utils/*.c -o tests/QueueTest.out &&\
	gcc -I utils tests/BinaryTreeTest.c utils/*.c -o tests/BinaryTreeTest.out &&\
	gcc -I utils tests/DirectedGraphTest.c utils/*.c -o tests/DirectedGraphTest.out
