CXX = gcc
CFLAGS = -I ../utils
OUTFILE = -o $@.out
INFILE = $@.c
UTILS = ../utils
STDPATTERN = $(CXX) $(CFLAGS) $(OUTFILE) $(INFILE)

01-01:
	$(STDPATTERN) $(UTILS)/BitVector.c
01-02:
	$(STDPATTERN)
01-03:
	$(STDPATTERN)
01-04:
	$(STDPATTERN)
01-05:
	$(STDPATTERN)
01-06:
	$(STDPATTERN)
01-07:
	$(STDPATTERN) $(UTILS)/BitVector.c
clean:
	rm *.out
