CXX = gcc
CFLAGS = -I ../utils

 01-01: 01-01.c ../utils/BitVector.c
	$(CXX) $(CFLAGS) -o 01-01.out ../utils/BitVector.c 01-01.c
 01-02: 01-02.c
	$(CXX) $(CFLAGS) -o 01-02.out 01-02.c
 01-03: 01-03.c
	$(CXX) $(CFLAGS) -o 01-03.out 01-03.c
